name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy-kintone:
    name: Deploy to Kintone
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
        env:
          NODE_ENV: production
          KINTONE_BASE_URL: ${{ secrets.KINTONE_BASE_URL }}
          KINTONE_APP_ID: ${{ secrets.KINTONE_APP_ID }}
          KINTONE_VIEW_ID: ${{ secrets.KINTONE_VIEW_ID }}
      - run: npm run deploy:kintone
        env:
          KINTONE_BASE_URL: ${{ secrets.KINTONE_BASE_URL }}
          KINTONE_APP_ID: ${{ secrets.KINTONE_APP_ID }}
          KINTONE_USERNAME: ${{ secrets.KINTONE_USERNAME }}
          KINTONE_PASSWORD: ${{ secrets.KINTONE_PASSWORD }}
