name: CI

on:
  pull_request:
  workflow_call:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm ci
      - run: npm run test

  check:
    name: Type Check
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm ci
      - run: npm run check:type

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm ci
      - run: npm run check:lint

  format:
    name: Format Check
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm ci
      - run: npm run check:format
