name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  deploy-kintone:
    name: Deploy to Kintone
    needs: test
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm ci
      - run: touch .env .env.development
      - run: npm run build
        env:
          NODE_ENV: production
      - uses: macrat/upload-kintone-customize-action@v1
        with:
          base-url: ${{ secrets.KINTONE_BASE_URL }}
          app-id: ${{ vars.KINTONE_APP_ID }}
          username: ${{ secrets.KINTONE_USERNAME }}
          password: ${{ secrets.KINTONE_PASSWORD }}
          desktop-js: ./dist/kintone/kintone-authenticator-desktop.js
          mobile-js: ./dist/kintone/kintone-authenticator-mobile.js
